try{
var s_GOc=function(a,b){var c=s_iu.Ea.document.documentElement,d=c.scrollHeight;a=Math.max(0,Math.min(c.scrollWidth-s_iu.Ea.window.innerWidth,a));b=Math.max(0,Math.min(d-s_iu.Ea.window.innerHeight,b));c.style.height=d+"px";c=s_iu.Ea.document.body.style;c.position="fixed";c.width="100%";c.left=-a+"px";c.top=-b+"px";s_EOc&&s_0i(s_EOc);s_iu.Ea.window.requestAnimationFrame?s_iu.Ea.window.requestAnimationFrame(function(){return void s_FOc(a,b)}):s_EOc=s__i(function(){return void s_FOc(a,b)},10)},s_FOc=
function(a,b){s_iu.Ea.window.scrollTo(a,b);s_EOc=null;s_iu.Ea.document.body.style.position="";s_iu.Ea.document.body.style.width="";s_iu.Ea.document.body.style.left="";s_iu.Ea.document.body.style.top="";s_iu.Ea.document.documentElement.style.height=""},s_iu={};s_iu.Ea={window:window,document:window.document};var s_HOc=s_na(),s_EOc=null;s_iu.Hta=function(a,b,c){if(a||b)s_HOc?(c=s_Ih(),s_GOc(c.x+a,c.y+b)):c?s_iu.Ea.window.scrollBy({top:b,left:a,behavior:"smooth"}):s_iu.Ea.window.scrollBy(a,b)};
s_iu.to=function(a,b,c){s_HOc?s_GOc(a,b):c?s_iu.Ea.window.scrollTo({top:b,left:a,behavior:"smooth"}):s_iu.Ea.window.scrollTo(a,b)};

}catch(e){_DumpException(e)}
try{
var s_vPe=function(a){var b=b||0;return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,b))}},s_CC=function(a,b,c){s_9e.call(this);this.Xf=null;this.oa=!1;this.vL=a;this.wa=c;this.ka=b||window;this.Bu=s_5e(this.usc,this)};s_8e(s_CC,s_9e);s_=s_CC.prototype;
s_.start=function(){this.stop();this.oa=!1;var a=s_wPe(this),b=s_xPe(this);a&&!b&&this.ka.mozRequestAnimationFrame?(this.Xf=s_l(this.ka,"MozBeforePaint",this.Bu),this.ka.mozRequestAnimationFrame(null),this.oa=!0):this.Xf=a&&b?a.call(this.ka,this.Bu):this.ka.setTimeout(s_vPe(this.Bu),20)};s_.stop=function(){if(this.isActive()){var a=s_wPe(this),b=s_xPe(this);a&&!b&&this.ka.mozRequestAnimationFrame?s_4g(this.Xf):a&&b?b.call(this.ka,this.Xf):this.ka.clearTimeout(this.Xf)}this.Xf=null};
s_.fire=function(){this.stop();this.usc()};s_.isActive=function(){return null!=this.Xf};s_.usc=function(){this.oa&&this.Xf&&s_4g(this.Xf);this.Xf=null;this.vL.call(this.wa,s_7e())};s_.yc=function(){this.stop();s_CC.zd.yc.call(this)};
var s_wPe=function(a){a=a.ka;return a.requestAnimationFrame||a.webkitRequestAnimationFrame||a.mozRequestAnimationFrame||a.oRequestAnimationFrame||a.msRequestAnimationFrame||null},s_xPe=function(a){a=a.ka;return a.cancelAnimationFrame||a.cancelRequestAnimationFrame||a.webkitCancelRequestAnimationFrame||a.mozCancelRequestAnimationFrame||a.oCancelRequestAnimationFrame||a.msCancelRequestAnimationFrame||null};

}catch(e){_DumpException(e)}
try{
var s_cVe=function(a,b){for(var c=0;c<a.length;++c){var d=s_j(a[c],b);if(d){d=d.match(/\S+/g)||[];for(var e=0;e<d.length;e++)"img.l"===d[e]&&s_Gd(a[c],s_xq)}}},s_dVe=function(a){a=s_xD(["xpdxpnd","mod"],a);s_cVe(a,"cact")},s_eVe=function(a){a=s_xD(["xpdxpnd","mod"],a);s_cVe(a,"eact")},s_fVe=function(a,b,c,d,e){function f(k,h){k=s_e(k);for(var l=k.next();!l.done;l=k.next())l=l.value,s_1d(l,"nlvc")||s_Wb(l)&&g.push(new s_Si(l,h))}if(!s_1d(b,"nlvc")){var g=[];"expanding"===c?(f(d,"show"),f(e,"hide"),
b=1):(f(d,"hide"),f(e,"show"),b=2);s_$p(g,{triggerElement:a||void 0,interactionContext:b,data:{ct:"knowledge_expander_toggle",cad:c}})}},s_yD=function(a){return s_K.contains(a,"xpdopen")},s_zD=function(a){return s_5h(a,"xpdbox")},s_xD=function(a,b){var c=[];a=b.querySelectorAll("."+a.join(", ."));for(var d=0;d<a.length;++d)s_zD(a[d])===b&&c.push(a[d]);return c},s_gVe=function(a){a=s_xD(["vk_arc"],a);return 0<a.length?a[0]:null},s_hVe=function(a,b){s_i.Sa(a,b);(a=s_zD(a))&&(b?s_Pi(a,"nlvc"):s_Oi(a,
"nlvc","1"))},s_iVe=function(a,b){var c=s_gVe(a);if(null!==c||a.querySelector("[data-inside-content-expander-position]"))null!==c&&(s__q(c,"expanded",b?"true":"false"),c.hasAttribute("aria-label")&&s_2q(c,b?"Show less":"Show more")),c="."+(b?"xpdclps":"xpdxpnd"),s_La(a.querySelectorAll("."+(b?"xpdxpnd":"xpdclps")),function(d){s_0q(d,"hidden")}),s_La(a.querySelectorAll(c),function(d){s__q(d,"hidden",!0)})},s_jVe=function(a,b){return(b=b?b.srcElement||b.target:null)&&b!==a&&s_4h(b,"LI","bili")?!1:!0},
s_kVe=function(a){var b=a.event;a=a.actionElement.el();var c=s_td(b);c&&(b=c);return s_jVe(a,b)},s_lVe=function(a,b){if(b){var c=s_xD(["vk_ard"],a);c=0<c.length?c[0]:null}else c=s_xD(["vk_aru"],a),c=0<c.length?c[0]:null;c&&s_K.Us(c,b?"vk_ard":"vk_aru",b?"vk_aru":"vk_ard");s_iVe(a,b)};

}catch(e){_DumpException(e)}
try{
s_a("QE1bwd");

var s_YG=function(a,b,c){s_9e.call(this);var d=this;this.container=a;this.wa=[];this.Aa=null;this.ka=this.container.sba();this.wa.push(s_Vu.subscribe("iehc",function(e){return s_9Ef(d,e)}));this.container.yea()&&this.wa.push(s_Vu.subscribe("r",function(e){d.ka===e&&d.container.y5(d.container.ld())}));this.Ba=b||1;this.oa=c||0};s_w(s_YG,s_9e);s_YG.prototype.yc=function(){s_La(this.wa,s_Xu);s_9e.prototype.yc.call(this)};
s_YG.prototype.expand=function(){this.container.Roa()?s_$Ef(this,!0):(this.container.y5(!0),this.container.s_(),s_9Ef(this,this.ka,s_aFf(this)))};s_YG.prototype.collapse=function(){this.container.Roa()?s_$Ef(this,!1):(this.container.y5(!1),this.container.hU(),s_bFf(this),s_9Ef(this,this.ka,s_aFf(this)))};
var s_$Ef=function(a,b){(new s_CC(function(){b||s_bFf(a);a.container.y5(b);s_cFf(a,b);s_9Ef(a,a.ka,s_aFf(a))})).start();a.Aa=Date.now()},s_dFf=function(a,b){b?(a.oa+=1,a.container.s_()):(a.oa=0,a.container.hU())},s_cFf=function(a,b){var c=a.container.mZb();c.find(function(d,e){if(a.container.gHa(d)||b&&1<a.Ba&&a.oa>e&&e<c.length-1)return!1;d=s_i.getComputedStyle(d,"transitionDuration");return""!==d&&"none"!==d&&"0s"!==d})?s__i(function(){s_dFf(a,b)},300):s_dFf(a,b)};
s_YG.prototype.lF=function(){return null!=this.Aa&&this.Aa+300>Date.now()};
var s_bFf=function(a){var b=a.container.w6a();b=b?b.getBoundingClientRect().top-8:a.ka.getBoundingClientRect().bottom-8;a.container.Roa()&&(b-=s_aFf(a));0>b&&(0,s_iu.Hta)(0,b)},s_aFf=function(a){var b=0;s_La(a.container.pYb(),function(c){a.container.h6b(c)?b+=c.scrollHeight:a.container.D5b(c)&&(b-=c.scrollHeight)},a);return b},s_9Ef=function(a,b,c){if(s_Nd(a.ka,b)){var d=s_4h(b,"g-expandable-content");if(d&&!a.container.gHa(d)&&0!==s_eFf(d)){var e=a.container.ld();if(e&&a.container.h6b(d)||!e&&a.container.D5b(d))a=
d.scrollHeight,a=c?a+c:a+b.scrollHeight,s_i.setStyle(d,"max-height",a+"px")}}},s_fFf=function(a,b,c){return new s_YG(a,void 0===b?1:b,void 0===c?0:c)};
var s_ZG=function(a){s_o.call(this,a.Ka);this.items=[];this.jB=[];this.Ia=null;this.actions=[];this.wa=null;this.Ba=!1;this.Aa=[];this.Na=this.getData("quie").Jb();this.La=this.getData("anim").Jb();this.Qa=this.getData("fcss").Jb();this.m8c=this.getData("rspae").Jb();this.Oa=this.getData("fae").Jb();this.oa=this.getData("npd").number(1);this.ka=this.getData("iexp").Jb()?this.oa:0;a=this.oa;var b=this.ka;this.Da=s_fFf(this,void 0===a?1:a,void 0===b?0:b);this.y0c=this.getData("slct").string("mnr-c")};
s_w(s_ZG,s_o);s_ZG.Ea=s_o.Ea;s_=s_ZG.prototype;s_.R8d=function(){return this.Aa};s_.s$a=function(){return this.Na};s_.q6d=function(){return this.y0c};s_.Aq=function(a){var b=this;s_gFf(this,this.getController(a.event.target).then(function(c){b.items.push(c);c.ld()!==b.ld()&&c.toggle()}))};s_.i2e=function(a){var b=this;s_gFf(this,this.getController(a.event.target).then(function(c){b.Ia=c}));s_hFf(this)};
s_.c2e=function(a){var b=this,c=a.event.target;s_gFf(this,this.getController(c).then(function(d){c.__mt=d.Mna();c.__eb=d.Gga();b.La||s_i.setStyle(c,"transition","none");b.jB.push(d)}));s_hFf(this)};s_.M1e=function(a){var b=this;s_gFf(this,this.getController(a.event.target).then(function(c){b.actions.push(c)}))};var s_gFf=function(a,b){a.Aa.push(b)};s_=s_ZG.prototype;s_.Jra=function(a){s_iFf(this,a)&&this.toggle()};s_.DUd=function(a){s_iFf(this,a)&&this.expand()};
s_.KNd=function(a){s_iFf(this,a)&&this.collapse()};s_.toggle=function(){this.Qha()?this.collapse():this.expand()};s_.Qha=function(){return this.ka>=this.oa};s_.expand=function(){var a=this;this.ka>=this.oa||this.Ba&&this.Da.lF()||s_Od(this.Aa).then(function(){a.Aa.length=0;a.Ba=!0;a.Da.expand()})};s_.collapse=function(){var a=this;this.ka<this.oa||this.Ba&&this.Da.lF()||s_Od(this.Aa).then(function(){a.Aa.length=0;a.Ba=!0;a.Da.collapse()})};s_.ld=function(){return 0<this.ka};s_.Roa=function(){return this.La};
s_.yea=function(){return!this.Na||this.Qa};s_.Raf=function(){return this.m8c};s_.s_=function(){this.ka+=1;this.Ba=!1;s_jFf(this);for(var a=s_e(this.actions),b=a.next();!b.done;b=a.next())b.value.vTf();this.trigger(s_1Ae,{rQ:this.wa});s_kFf(this,this.wa,"expanding");this.wa=null;this.Oa&&(a=s_tMb(this.getRoot().el(),s_2h))&&a.focus()};
s_.hU=function(){this.ka=0;this.Ba=!1;s_jFf(this);for(var a=s_e(this.actions),b=a.next();!b.done;b=a.next())b.value.FRf();this.trigger(s_2Ae,{rQ:this.wa});s_kFf(this,this.wa,"collapsing");this.wa=null};s_.y5=function(a){1>=this.oa&&(this.ka=a?this.oa:0);for(var b=s_e(this.items),c=b.next();!c.done;c=b.next())c=c.value,a?c.expand():c.collapse()};
var s_hFf=function(a){s_Od(a.Aa).then(function(){var b=a.w6a();if(b){var c=a.pYb().filter(function(d){return d.id}).map(function(d){return d.id});b.setAttribute("aria-controls",c.join(" "))}})};s_=s_ZG.prototype;s_.sba=function(){return this.getRoot().el()};s_.v6a=function(){return this.Ca("gI9xcc").el()};s_.fba=function(){return s_L(this,"AHe6Kc").el()};s_.cPc=function(){return s_L(this,"bnBfGc").el()};s_.w6a=function(){return this.Ia?this.Ia.getRoot().el():null};
s_.mZb=function(){for(var a=[],b=s_e(this.jB),c=b.next();!c.done;c=b.next())c=c.value,0!==c.Mna()&&a.push(c.getRoot().el());return a};s_.pYb=function(){return[].concat(s_Kb(s_lFf(this,0)),s_Kb(s_lFf(this,1)))};s_.E$d=function(a){return this.Ia?this.Ia.f_b(a):[]};var s_eFf=function(a){return void 0!==a.__mt?a.__mt:0};s_=s_ZG.prototype;s_.kye=function(a){return 3===s_eFf(a)};s_.oxe=function(a){return 2===s_eFf(a)};s_.h6b=function(a){return 0===s_mFf(a)};s_.D5b=function(a){return 1===s_mFf(a)};
s_.gHa=function(a){return 2===s_mFf(a)};var s_mFf=function(a){return void 0!==a.__eb?a.__eb:2},s_jFf=function(a){a.sba().setAttribute("aria-expanded",String(a.Qha()))},s_kFf=function(a,b,c){if(!b||s_Wb(b)){var d=s_lFf(a,0),e=s_lFf(a,1);s_fVe(b,a.sba(),c,d,e)}},s_iFf=function(a,b){return s_kVe(b)?(a.wa=b.event.target,!0):!1},s_lFf=function(a,b){var c=[];a=s_e(a.jB);for(var d=a.next();!d.done;d=a.next())d=d.value,d.Gga()===b&&c.push(d.getRoot().el());return c};s_ZG.prototype.Eb=function(){this.Da.dispose()};
s_M(s_ZG.prototype,"k4Iseb",function(){return this.Eb});s_M(s_ZG.prototype,"em9Kzd",function(){return this.pYb});s_M(s_ZG.prototype,"Y4cWJb",function(){return this.mZb});s_M(s_ZG.prototype,"kgs1Xc",function(){return this.w6a});s_M(s_ZG.prototype,"nKoqoe",function(){return this.cPc});s_M(s_ZG.prototype,"zRB1Df",function(){return this.fba});s_M(s_ZG.prototype,"hOh3bf",function(){return this.v6a});s_M(s_ZG.prototype,"qrngke",function(){return this.sba});s_M(s_ZG.prototype,"Yzm1wf",function(){return this.hU});
s_M(s_ZG.prototype,"sMv6wf",function(){return this.s_});s_M(s_ZG.prototype,"FoYd",function(){return this.Raf});s_M(s_ZG.prototype,"iGSKCe",function(){return this.yea});s_M(s_ZG.prototype,"rXu79",function(){return this.Roa});s_M(s_ZG.prototype,"sMVRZe",function(){return this.ld});s_M(s_ZG.prototype,"vhaaFf",function(){return this.collapse});s_M(s_ZG.prototype,"KoToPc",function(){return this.expand});s_M(s_ZG.prototype,"ZhEbuc",function(){return this.Qha});s_M(s_ZG.prototype,"ornU0b",function(){return this.toggle});
s_M(s_ZG.prototype,"fW2qAb",function(){return this.KNd});s_M(s_ZG.prototype,"AvkpRc",function(){return this.DUd});s_M(s_ZG.prototype,"yELBLe",function(){return this.Jra});s_M(s_ZG.prototype,"Z6bwpe",function(){return this.M1e});s_M(s_ZG.prototype,"AgioGc",function(){return this.c2e});s_M(s_ZG.prototype,"GsRPff",function(){return this.i2e});s_M(s_ZG.prototype,"Nh5q2c",function(){return this.Aq});s_M(s_ZG.prototype,"vcEgJc",function(){return this.q6d});s_M(s_ZG.prototype,"MT9BLc",function(){return this.s$a});
s_M(s_ZG.prototype,"d74pFb",function(){return this.R8d});s_U(s_hSa,s_ZG);


s_b();

}catch(e){_DumpException(e)}
// Google Inc.
